version: '3.8'

services:
  db:
    image: mysql:5.7.33
    environment:
      TZ: 'Asia/Tokyo'
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
    volumes:
      - mysql-data:/var/lib/mysql

  api:
    build:
      context: ./api
      args:
        WORKDIR: $WORKDIR
    environment:
      API_DOMAIN: "localhost:$FRONT_PORT"
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
    volumes:
      - ./api:/$WORKDIR:cached
      - gem-data:/usr/local/bundle:cached
    depends_on:
      - db
    ports:
      - "$API_PORT:$CONTAINER_PORT"
    tty: true
    stdin_open: true

  front:
    build:
      context: ./front
      args:
        WORKDIR: $WORKDIR
        CONTAINER_PORT: $CONTAINER_PORT
        API_URL: "http://localhost:$API_PORT"
    command: yarn run dev
    volumes:
      - ./front:/$WORKDIR
      - yarn-cache:/usr/local/share/.cache/yarn/v6:cached
      - node_modules:/node_modules
    ports:
      - "$FRONT_PORT:$CONTAINER_PORT"
    depends_on:
      - api

volumes:
  mysql-data:
  gem-data:
  yarn-cache:
  node_modules:
