version: 2.1

jobs:
  test_api:
    docker:
      - image: circleci/ruby:2.7.2
        environment:
          RAILS_ENV: test
          DB_HOST: 127.0.0.1
          DB_USER: 'root'
          DB_ROOT_PASSWORD: 'password'
      - image: circleci/mysql:5.7.33
        environment:
          MYSQL_USER: root
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: app_test

    working_directory: ~/repo

    steps:
      - checkout

      # Wait for the DB image to start up
      - run:
          name: Install dockerize
          command: wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && sudo tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
          environment:
            DOCKERIZE_VERSION: v0.6.1
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://127.0.0.1:3306 -timeout 3m

      # restore gem from cache
      - restore_cache:
          keys:
            - gem-cache-v1-{{ checksum "~/repo/api/Gemfile.lock" }}
            - gem-cache-v1-
          working_directory: ~/repo/api

      # gem install
      - run:
          command: |
            gem install bundler
            bundle config set path 'vendor/bundle'
            bundle install --jobs=4 --retry=3
          working_directory: ~/repo/api

      - save_cache:
          key: gem-cache-v1-{{ checksum "~/repo/api/Gemfile.lock" }}
          paths:
            - ~/repo/api/vendor/bundle
          working_directory: ~/repo/api

      # Database setup
      - run:
          command: bundle exec rails db:create
          working_directory: ~/repo/api
      - run:
          command: bundle exec rails db:migrate
          working_directory: ~/repo/api

      - run:
          name: create directory to store test results
          command: mkdir /tmp/test-results
          working_directory: ~/repo/api

      # run tests
      - run:
          name: RSpec
          command: |
            bundle exec rspec $(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings) \
              || (printf "====== RETRYING...\n\n\n"; bundle exec rspec --only-failures)
          working_directory: ~/repo/api

      # collect reports
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results
      - store_artifacts:
          path: /home/circleci/repo/tmp/screenshots

  test_front:
    docker:
      - image: circleci/node:15.8.0-browsers
        environment:
          NODE_ENV: test

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "~/repo/front/package.json" }}
          working_directory: ~/repo/front
      - run:
          name: install-packages
          command: npm install --legacy-peer-deps
          working_directory: ~/repo/front
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "~/repo/front/package.json" }}
          working_directory: ~/repo/front
      - run:
          name: test
          command: npm run test
          working_directory: ~/repo/front

workflows:
  version: 2
  test:
    jobs:
      - test_api:
          filters:
            branches:
              ignore: main
      - test_front:
          filters:
            branches:
              ignore: main
